% This function aims to write the controlDict file containing the
% information that controls the whole CFD process
% files
%       Author  : Gabriel Buendia
%       Version : 1
% Inputs:
%       solver         -> Name of the OpenFOAM solver used
%       startTime      -> Starting time of the simulation
%       endTime        -> Ending time of the simulation
%       deltaT         -> Time step
%       writeInterval  -> Interval for writing outputs
%       writePrecision -> Number of decimals used in calculations
%       timePrecision  -> Number of decimals used for the temporal steps
function ofControlDict(path,solver,startTime,endTime,deltaT,writeInterval,writePrecision,timePrecision) 
fileName = fopen(append(path,'controlDict'),'w');
string = (['/','*--------------------------------*- C++ -*----------------------------------*','\\',' \n' ...
           '| =========                 |                                                 | \n' ...
           '| \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           | \n' ...
           '|  \\\\    /   O peration     | Version:  dev                                   | \n' ...
           '|   \\\\  /    A nd           | Web:      www.OpenFOAM.org                      | \n' ...
           '|    \\\\/     M anipulation  |                                                 | \n' ...
           '\\','*---------------------------------------------------------------------------*','/',' \n\n' ...
           'FoamFile\n' ...
            '{\n' ...
            '    version     2.0;\n' ...
            '    format      ascii;\n' ...
            '    class       dictionary;\n' ...
            '    location    "system";\n' ...
            '    object      controlDict;\n' ...
            '}\n' ...
            '// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //\n\n' ...
            'application ',solver,';\n\n' ...
            'startFrom latestTime;\n\n' ...
            'startTime ',num2str(startTime),';\n\n' ...
            'stopAt endTime;\n\n' ...
            'endTime ',num2str(endTime),';\n\n' ...
            'deltaT ',num2str(deltaT),';\n\n' ...
            'writeControl timeStep;\n\n' ...
            'writeInterval ',num2str(writeInterval),';\n\n' ...
            'purgeWrite 2;\n\n' ...
            'writeFormat ascii;\n\n' ...
            'writePrecision ',num2str(writePrecision),';\n\n' ...
            'writeCompression no;\n\n' ...
            'timeFormat general;\n\n' ...
            'timePrecision ',num2str(timePrecision),';\n\n' ...
            'runTimeModifiable yes;\n\n' ...
            'libs\n' ...
            '(\n' ...
            '    "libforces.so"\n' ...
            ');\n\n' ...
            'functions\n' ...
            '{\n' ...
            '    #include "wingForces";\n' ...
            '    #include "yPlus";\n' ...
            '    #include "wallShearStress";\n' ...
            '}\n']);
fprintf(fileName,string);
fclose(fileName);
end
