% This function aims to write the decomposeParDict file containing the
% information to split the domain when simulating in parallel (HPC)
% files
%       Author  : Gabriel Buendia
%       Version : 1
% Inputs:
%       path  -> Path to save the file locally
%       cores -> Number of available cores
function ofDecomposeParDict(path,cores) 
fileName = fopen(append(path,'decomposeParDict'),'w');
string = (['/','*--------------------------------*- C++ -*----------------------------------*','\\',' \n' ...
           '| =========                 |                                                 | \n' ...
           '| \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           | \n' ...
           '|  \\\\    /   O peration     | Version:  dev                                   | \n' ...
           '|   \\\\  /    A nd           | Web:      www.OpenFOAM.org                      | \n' ...
           '|    \\\\/     M anipulation  |                                                 | \n' ...
           '\\','*---------------------------------------------------------------------------*','/',' \n\n' ...
           'FoamFile\n' ...
           '{\n' ...
           '    version     2.0;\n' ...
           '    format      ascii;\n' ...
           '    class       dictionary;\n' ...
           '    object      decomposeParDict;\n' ...
           '}\n' ...
           '// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //\n\n' ...
           'numberOfSubdomains ',num2str(cores),';\n\n' ...
           'method          scotch;\n\n' ...
           'coeffs\n' ...
           '{\n' ...
           '    n           (2 2 1);\n' ...
           '}\n\n' ...
           'distributed     no;\n\n' ...
           'roots           ( );\n\n\n' ...
           '// ************************************************************************* //']);
fprintf(fileName,string);
fclose(fileName);
end